# Configuración de Desarrollo (se activa con el perfil 'dev')
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # 'update' está bien para desarrollo
      ddl-auto: update
    show-sql: true