# Configuración de Producción (se activa con el perfil 'prod')
spring:
  datasource:
    driverClassName: org.postgresql.Driver

    # Leemos las variables de entorno del servidor
    url: ${DB_URL}          # ej: jdbc:postgresql://servidor.com:5432/basedatos
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # 'validate' es más seguro para producción. No intenta crear ni borrar tablas.
      ddl-auto: validate
    show-sql: false # No mostramos SQL en producción por rendimiento