server:
  port: 8080

spring:
  application:
    name: order-management-system

  # Perfil por defecto
  # Le decimos a Spring que si no le especificamos un perfil, active el de "dev"
  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  springdoc:  
    packagesToScan: com.meli.ordermanagementsystem.controller